/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'variant',
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}', './node_modules/@tremor/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            colors: {
                background: {
                    light: 'var(--color-background-light)',
                    base: 'var(--color-background-base)',
                    dark: 'var(--color-background-dark)',
                },
                primary: {
                    light: 'var(--color-primary-light)',
                    base: 'var(--color-primary-base)',
                    dark: 'var(--color-primary-dark)',
                },
                text: {
                    light: 'var(--color-text-light)',
                    base: 'var(--color-text-base)',
                    dark: 'var(--color-text-dark)',
                },
                header: 'var(--color-header)',
                // primary: {
                //     50: '#ecf4ff',
                //     100: '#dceaff',
                //     200: '#bfd7ff',
                //     300: '#99bcff',
                //     400: '#7094ff',
                //     500: '#4f6eff',
                //     600: '#3044fb',
                //     700: '#2331df',
                //     800: '#202eb3',
                //     900: '#1e297b',
                //     950: '#141a52',
                // },
                // secondary: {
                //     50: '#fcf8f0',
                //     100: '#f9f0db',
                //     200: '#f2ddb6',
                //     300: '#eac78b',
                //     400: '#e0a657',
                //     500: '#d98d36',
                //     600: '#ca752c',
                //     700: '#a85c26',
                //     800: '#874a25',
                //     900: '#6d3d21',
                //     950: '#3a1e10',
                // },
                // text: {
                //     50: '#f6f6f6',
                //     100: '#e7e7e7',
                //     200: '#d1d1d1',
                //     300: '#b0b0b0',
                //     400: '#888888',
                //     500: '#6b6b6b',
                //     600: '#5d5d5d',
                //     700: '#4f4f4f',
                //     800: '#454545',
                //     900: '#3d3d3d',
                //     950: '#262626',
                // },
            },
        },
    },
    plugins: [require('@headlessui/tailwindcss')],
};
