name: Release Version

on:
    push:
        branches:
            - main

jobs:
    build-release:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # Important to fetch tags

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install Dependencies
              run: npm install

            - name: Package & Publish
              run: npm run publish:mac
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
